name: PR builder
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build and run tests
    runs-on: ubuntu-latest
    if: github.repository_owner == 'hazelcast'

    steps:
      - name: Read Java Config
        run: cat ${{ github.workspace }}/hazelcast/.github/java-config.env >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - name: Set up Apache Maven Central
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          cache: 'maven'

      - name: Build
        run: |
          mvn clean package
